### ISSUE TITLE
Popupmenu: Unwanted navigation occurs if the menu is destroyed when clicking a menu item

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise-ng#1046]
**Describe the bug**
If a click on a menu item (e.g. `soho-popupmenu-label`) causes the menu to be destroyed, an unwanted navigation occurs.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-950-l5edgr?file=src%2Fapp%2Fapp.component.html
2. Open menu
3. Click on A (nothing will happen, by design)
4. Click on B (nothing will happen, by design)
5. Click on C 

**Result** 
An unwanted navigation occurs (see the address bar with added /#). 

All that happens is that when clicking C, the `showMenu` flag is set to false, causing the popupmenu to be destroyed due to its `*ngIf`. Not a very common use case perhaps, but let's say a menu click opens another view that doesn't include the popupmenu.

This causes problem when the app also uses the Angular Router.

**Expected behavior**
A menu item click should never cause a navigation change.

**Version**
- ids-enterprise-ng: 9.5.0

**Additional context**
Might be an issue in the underlying popupmenu control rather than the angular component.

Related to https://github.com/infor-design/enterprise-ng/issues/807. 

![navigation-issue](https://user-images.githubusercontent.com/1101770/119491910-caaf6580-bd5e-11eb-8632-020c4e087671.gif)

**Comment by volante007** [comment]
Can be reproduced in the popupmenu control as well.
https://design.infor.com/code/ids-enterprise/latest/demo/components/popupmenu/test-destroy.html

1. Open dev console, execute below
```
$('#popupmenu-2 li:first-child').on('click', function () {
          $("#popupmenu-trigger").destroy();
        });
```
2. Open menu and click "Menu Option #1"
3. Notice page navigation change

**Comment by tmcconechy** [comment]
We probably need to do a stop propagation in the click code.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by volante007** [comment]
I can still reproduce this.

In stackblitz below, v4.54.0 is used. Click option C from the menu. Was this fixed only in enterprise, but still issue in enterprise-ng perhaps?

https://stackblitz.com/edit/ids-quick-start-1030-ppjx8v?file=src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
can you take another look @ericangeles ?

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/popupmenu/test-unwanted-navigation-when-menu-destroyed.html
![Screen Recording 2021-09-23 at 5 41 43 PM](https://user-images.githubusercontent.com/84306838/134498106-103bf3eb-b65e-4bd5-b743-458c9da62a7f.GIF)

Moving this ticket to Done.

Thanks!
