### ISSUE TITLE
Header columns and body columns are missaligned in some cases

### ISSUE THREAD

**Issue by vict0ry** [infor-design/enterprise-ng#416]
**Describe the bug**
The column spliters are not aligned for the datagrids when scroll bar disappears after Row Height change.

**To Reproduce**
1) Set datagrid configuration rowHeight to true.
2) Open datagrid with some data so scroll bar height is there but there shouldn't bee too much data so we scrollbar will disappear after we make columns height smaller. 
3) Make columns smaller so scrollbar disappear

**Expected behavior**
Expect to measure new width of columns including scrollbar and reset it. 

**Version**
"ids-enterprise-ng": "5.0.0",

**Screenshots**
![image1](https://user-images.githubusercontent.com/14180358/55732092-a3c93480-5a1b-11e9-8f62-822d43a82eab.JPG)
![image2](https://user-images.githubusercontent.com/14180358/55732102-a7f55200-5a1b-11e9-90a1-16df6fc07d87.JPG)
![image3](https://user-images.githubusercontent.com/14180358/55732104-a88de880-5a1b-11e9-9c4c-425fc39641b9.JPG)

**Platform**
Win 10, Chrome.
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
These look like screen shots of your application. Can you
- test this on 5.2.1 latest as we fixed a few alignment issues like this
- if not working upload an example we can run?

**Comment by vict0ry** [comment]
> These look like screen shots of your application. Can you
> 
> * test this on 5.2.1 latest as we fixed a few alignment issues like this
> * if not working upload an example we can run?

Hello Tim, 
thank you for quick reply.
Just upgraded app to the 5.2.1 version. Issue is still there.

**Comment by tmcconechy** [comment]
Ok, can you reproduce it in our sample app? Or do you have an example you can add to the issue?

**Comment by tmcconechy** [comment]
We fixed a few more of these issues on 5.3.0 and on again to 5.4.0 (4.19).
Not sure what case this is? Do you have percent columns? May need more info to reproduce.

**Comment by bthharper** [comment]
@tmcconechy  I am getting issues like this too, normally when changing the size of a column, and then resizing the browser.  Refreshing the contents (using a coded Refresh button) causes the columns and grids to re-align.

I would have thought we could recreate the same issue with the examples.

**Comment by tmcconechy** [comment]
Can you try with the very latest build loaded on and see if you can reproduce anymore? I fixed some cases as noted here https://github.com/infor-design/enterprise/pull/2089 and now release the cache so i thought that would get rid of this issue once and for all?

**Comment by bthharper** [comment]
@tmcconechy - I guess `ids-enterprise-ng@dev` would be okay?

**Comment by tmcconechy** [comment]
Yeah Should be now since we just updated it My fix was 8 days ago in EP

**Comment by bthharper** [comment]
I'm running with the latest code (from NG), and one issue I see is that when I load my page and the grid fills the page when I resize the grid does not resize (always).

![image](https://user-images.githubusercontent.com/8340092/57786787-08b72f00-772c-11e9-9214-77808d49f652.png)

![image](https://user-images.githubusercontent.com/8340092/57787336-1325f880-772d-11e9-988e-d06fd7dbc7f7.png)

If I refresh the data then it snaps back (due to a redraw internally).   Often, when I refresh the data the columns will re-align.

I am not sure if the application menu is causing some of these issues.

**Comment by tmcconechy** [comment]
Ok, i am aware that it doesnt resize the whole grid on resize (was a choice we could rethink).
But if its causing alignment issues we should track that down as an EP issue? Can you clarify the general steps and maybe we can make an example? This sound right?

- open page with grid and a button that will reload data 
- menu will be open
- close menu
- notice grid doesnt fill?
- hit reload
- notice columns misalign

**Comment by tmcconechy** [comment]
I was not able to reproduce this issue to the level i could do anything with it on the latest version. If you have any examples on the latest stuff we can test please add and i will reopen. But i suspect this issue has been resolved along the way on other tickets.
