### ISSUE TITLE
SOHO-7748: IE11 - Datepicker formcontrol not clearing using keyboard

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise-ng#51]
Issue applies only to IE11 and Edge. Using a datepicker in an angular formcontrol/formgroup setup. If there is a value in the datepicker field and you use the datepicker dialog to clear the value, the underlying control value updates correctly (clears it out). But, if you use the keyboard, either backspace or delete key, to clear out the value the underlying control value does not get cleared. In order to reproduce this I modified the soho angular example for form group validation to include a datepicker. It's in PR627.

Steps to reproduce:
1. In Enterprise-NG demo.
2. Open V, Validation - FormGroup & Mask.
3. In the Standard Date field, use the picker dialog to select a value.
4. Note in the model text that the 'Date Value' value shows correctly.
5. Using the datepicker dialog, click the Clear button. 
6. Note the Date Value in the model updates correctly (now empty).
7. Repeat step 3, note the model shows a value again.
8. Now use the keyboard delete or backspace key to clear the value in the picker field then tab elsewhere.
9. At this point using Chrome, the displayed model value shows correctly (is cleared). But, using IE11 or Edge, the displayed model value does not clear (shows the value from step 7). 

See attached screen print.

This is a bit of a nasty bug - as far as the user can tell the value was cleared but the form gets submitted with the uncleared value. Really need this fix migrated to 4.3.5 if possible.

![untitled](https://user-images.githubusercontent.com/814283/40735988-ada7ba56-640a-11e8-85bd-1967a720f380.jpg)

**Comment by tmcconechy** [comment]
@bthharper or @pwpatton do you have any initial thoughts on this issue?

Also what version are you on when this was last tested. We did some PR's that changed the way the datepicker works and i'm wondering if this is either caused by or fixed by that change?

**Comment by dmcodrum** [comment]
Recently verified that this issue still exists with version 4.9. We first noticed it in v 4.3.5. To be clear - it only occurs in IE 11 and Edge.

**Comment by tmcconechy** [comment]
One thing i can see is that in IE 11 the change event is not firing when you backspace the field down. You can see this in the console. But it does fire if you select all the text and hit backspace and then tab out. 

If i destroy mask in the console with `$('datepicker').data('mask').destroy()` then the issue doesnt happen so must be an issue in the mask component.

But also there is plenty of bugs around IE not having change fire https://www.google.com/search?q=IE+not+firing+change+event&oq=IE+not+firing+change+event+&aqs=chrome..69i57j0.6910j0j7&sourceid=chrome&ie=UTF-8

We have a related workaround in https://github.com/infor-design/enterprise/blob/master/src/components/mask/mask-input.js#L165

**Comment by brianjuan** [comment]
Is this testable on http://4100-beta1-enterprise.demo.design.infor.com/components/datepicker/ ?

**Comment by dmcodrum** [comment]
The way I tested it was in the Angular demo under 'Validation - Form Group & Mask'. Use IE11 & Edge for testing. The display of the Date Value at the bottom of the form should clear when you use the keyboard to clear out the date value in the datepicker.

**Comment by clepore** [comment]
@brianjuan While the ticket refers to a bug in EnterpriseNG, the source of the bug was in Enterprise. I'm not sure if you can see the bug in Enterprise components or not. I would skip this one.

**Comment by tmcconechy** [comment]
How do we mark them? Just move them direct to "Done" ?

**Comment by clepore** [comment]
Yep, I think anything that doesn't need QA, should be moved to done.

**Comment by tmcconechy** [comment]
I think this is done now.
