### ISSUE TITLE
Context Menu: Wrong menu is displayed when nested on iOS & Android

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#969]
**Describe the bug**
When a parent container P has a context menu, and it has some child C with another context menu, the menu for P is displayed when C is long-pressed on iOS and Android. But the menu for C is correctly displayed when right-clicking in a desktop browser

**To Reproduce**
Given a component with the following template:
```html
<div class="row top-padding">
  <div class="twelve columns">
    <ul soho-context-menu menu="parent" style="height: 500px; border: 1px solid red; padding: 10px;">
      <p style="color: red;">Parent</p>
      <li soho-context-menu menu="child" style="height: 100px; border: 1px solid orange;">
        <p style="color: orange;">Child</p>
      </li>
      <ul soho-popupmenu id="child">
        <li soho-popupmenu-item><a>Child 1</a></li>
        <li soho-popupmenu-item><a>Child 2</a></li>
        <li soho-popupmenu-item><a>Child 3</a></li>
      </ul>
    </ul>
    <ul soho-popupmenu id="parent">
      <li soho-popupmenu-item><a>Parent 1</a></li>
      <li soho-popupmenu-item><a>Parent 2</a></li>
      <li soho-popupmenu-item><a>Parent 3</a></li>
    </ul>
  </div>
</div>
```

1. Long-press in the Parent container
2. The Parent context menu is displayed
3. Long-press in the Child container
4. The Parent context menu is displayed

**Expected behavior**
The Child context menu should be displayed when long-pressing the Child container.

**Version**
- ids-enterprise-ng: 9.1.0 (also present in older versions)

**Screenshots**

https://user-images.githubusercontent.com/4991954/104431355-14559b80-5588-11eb-806d-acf1baff8e49.mp4

https://user-images.githubusercontent.com/4991954/104431363-1586c880-5588-11eb-825d-08b63393709e.mp4

**Platform**
 - iPhone, Android phones, any browser with an iOS/Android User Agent

**Additional context**
Homepages issue: https://jira.infor.com/browse/LIME-5711

Related: https://github.com/infor-design/enterprise-ng/issues/699

**Comment by katieinfor** [comment]
May want to retest this issue.

**Comment by tmcconechy** [comment]
@anhallbe we fixed https://github.com/infor-design/enterprise-ng/issues/987 im not 100% sure but its possible it could have helped here. If you can a chance can you try with that version?

**Comment by volante007** [comment]
The issue is still reproducible

**Comment by tmcconechy** [comment]
Still working on this @davidcarlsonberg ?

**Comment by davidcarlsonberg** [comment]
Hi @tmcconechy, yes I can take this one unless it's been reassigned?

**Comment by tmcconechy** [comment]
Nope not yet please go for it 👍

**Comment by tmcconechy** [comment]
@volante007 and @anhallbe would you be able to test https://github.com/infor-design/enterprise-ng/pull/1196
It looks good to me..

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by radovaniljic** [comment]
@tmcconechy this is still reproducible in the latest version, but only when using an actual mobile device. It can be tested here: https://ids-quick-start-1450-mkdsma.stackblitz.io (same code as in the original post)

**Comment by tmcconechy** [comment]
@radovaniljic might be better to just make a net new issue and include this one for history. Thinking we need the mobile steps here and to simplify the history for a developer.
